(package "sunrise-commander" "6" "Two-pane file manager based on Dired")
(source melpa)
(source gnu)

(package-file "sunrise-commander.el")
(package-file "sunrise-x-buttons.el")
(package-file "sunrise-x-checkpoints.el")
(package-file "sunrise-x-loop.el")
(package-file "sunrise-x-mirror.el")
(package-file "sunrise-x-modeline.el")
(package-file "sunrise-x-old-checkpoints.el")
(package-file "sunrise-x-popviewer.el")
(package-file "sunrise-x-tabs.el")
(package-file "sunrise-x-tree.el")
(package-file "sunrise-x-w32-addons.el")
