(package "sunrise" "6" "Two-pane file manager based on Dired")
(source melpa)
(source gnu)

(package-file "sunrise.el")
(package-file "sunrise-buttons.el")
(package-file "sunrise-checkpoint.el")
(package-file "sunrise-loop.el")
(package-file "sunrise-mirror.el")
(package-file "sunrise-modeline.el")
(package-file "sunrise-popviewer.el")
(package-file "sunrise-tabs.el")
(package-file "sunrise-tree.el")
(package-file "sunrise-w32.el")
